version: "3.7"

services:
  spip:
    restart: unless-stopped
    networks:
      - db
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spip-${COMPOSE_PROJECT_NAME:?err}.rule=Host(`${COMPOSE_PROJECT_NAME}.${DOMAIN_NAME:-recette.tech}`)"
      - "traefik.http.routers.spip-${COMPOSE_PROJECT_NAME}.entrypoints=https"
      - "traefik.http.routers.spip-${COMPOSE_PROJECT_NAME}.service=spip-${COMPOSE_PROJECT_NAME}"
      - "traefik.http.services.spip-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"

      - "traefik.http.routers.spip-${COMPOSE_PROJECT_NAME}.tls.certresolver=myresolver"

  phpmyadmin:
    restart: unless-stopped
    networks:
      - db
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma-${COMPOSE_PROJECT_NAME}.rule=Host(`pma-${COMPOSE_PROJECT_NAME}.${DOMAIN_NAME:-recette.tech}`)"
      - "traefik.http.routers.pma-${COMPOSE_PROJECT_NAME}.entrypoints=https"
      - "traefik.http.routers.pma-${COMPOSE_PROJECT_NAME}.service=pma-${COMPOSE_PROJECT_NAME}"
      - "traefik.http.services.pma-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"

      - "traefik.http.routers.pma-${COMPOSE_PROJECT_NAME}.tls.certresolver=myresolver"

  db:
    restart: unless-stopped
    networks:
      - db

networks:
  db:
  traefik:
    external:
      name: "${TRAEFIK_NETWORK}"
