version: "3.7"

services:
  spip:
    networks:
      - db
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spip.rule=Host(`${COMPOSE_PROJECT_NAME}.${DOMAIN_NAME:-recette.tech}`)"
      - "traefik.http.routers.spip.entrypoints=http"
      - "traefik.http.routers.spip.service=spip"
      - "traefik.http.services.spip.loadbalancer.server.port=80"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"

  phpmyadmin:
    networks:
      - db
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`pma-${COMPOSE_PROJECT_NAME}.${DOMAIN_NAME:-recette.tech}`)"
      - "traefik.http.routers.pma.entrypoints=http"
      - "traefik.http.routers.pma.service=pma"
      - "traefik.http.services.pma.loadbalancer.server.port=80"
      - "traefik.docker.network=${TRAEFIK_NETWORK}"

  db:
    networks:
      - db

networks:
  db:
  traefik:
    external:
      name: "${TRAEFIK_NETWORK}"
