version: "3.7"
services:
  db:
    image: mariadb:10.5.1
    environment:
      MYSQL_DATABASE: spip
      MYSQL_USER: spip
      MYSQL_PASSWORD: "${SPIP_DB_PASS:-changez_moi}"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - mariadb:/var/lib/mysql

  spip:
    build: ./spip
    depends_on:
      - db
    environment:
      SPIP_DB_HOST: db
      SPIP_DB_NAME: spip
      SPIP_DB_LOGIN: spip
      SPIP_DB_PASS: "${SPIP_DB_PASS:-changez_moi}"

      SPIP_ADMIN_PASS: "${SPIP_ADMIN_PASS:-changez_moi}"
      SPIP_ADMIN_NAME: "${SPIP_ADMIN_NAME:-Spip}"
      SPIP_ADMIN_LOGIN: "${SPIP_ADMIN_LOGIN:-spip}"
      SPIP_ADMIN_EMAIL: "${SPIP_ADMIN_EMAIL:-spip@spip}"
    volumes:
      - ${MOUNTS:-./mounts}/IMG:/var/www/html/IMG/
      - ${MOUNTS:-./mounts}/plugins/:/var/www/html/plugins/
      - ${MOUNTS:-./mounts}/lib/:/var/www/html/lib/
      - ${MOUNTS:-./mounts}/tmp/:/var/www/html/tmp/
      - ${MOUNTS:-./mounts}/local/:/var/www/html/local/
      - ${MOUNTS:-./mounts}/htaccess:/var/www/html/.htaccess

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    volumes:
     - /sessions

volumes:
  mariadb:
